# Generated by Django 5.2.1 on 2026-06-07 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, db_index=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='igrejas/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['cidade', 'estado'], name='API_igreja_cidade_84a449_idx'), models.Index(fields=['ativo'], name='API_igreja_ativo_712231_idx')],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('ministerio', 'Ministério'), ('classe', 'Classe / Escola Sabatina'), ('desbravadores', 'Desbravadores'), ('aventureiros', 'Aventureiros'), ('musica', 'Música / Louvor'), ('jovens', 'Jovens'), ('outro', 'Outro')], default='ministerio', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='grupos/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='API.igreja')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fim', models.DateTimeField()),
                ('visibilidade', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado (somente o grupo)')], default='publico', max_length=10)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente de aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=12)),
                ('recorrencia', models.CharField(choices=[('nenhuma', 'Não se repete'), ('diaria', 'Diariamente'), ('semanal', 'Semanalmente'), ('mensal', 'Mensalmente')], default='nenhuma', max_length=10)),
                ('recorrencia_ate', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('motivo_rejeicao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='API.grupo')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='API.igreja')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('talvez', 'Talvez'), ('cancelado', 'Cancelado')], default='confirmado', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='API.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('visitante', 'Visitante'), ('membro', 'Membro'), ('anciao', 'Ancião'), ('pastor', 'Pastor'), ('admin_igreja', 'Administrador da igreja')], default='visitante', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('rejeitado', 'Rejeitado'), ('inativo', 'Inativo')], default='pendente', max_length=12)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_aprovados', to=settings.AUTH_USER_MODEL)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='API.igreja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro da igreja',
                'verbose_name_plural': 'Membros da igreja',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='chat/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='API.grupo')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=40)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('anonima', models.BooleanField(default=False, help_text='Se marcado, os votos não revelam quem votou.')),
                ('prazo_votacao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('encerrada', 'Encerrada')], default='aberta', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas_criadas', to=settings.AUTH_USER_MODEL)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to='API.igreja')),
            ],
            options={
                'verbose_name': 'Pauta',
                'verbose_name_plural': 'Pautas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('bio', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_super_admin', models.BooleanField(db_index=True, default=False)),
                ('fonte_grande', models.BooleanField(default=False)),
                ('notificacoes_email', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('igreja_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_principais', to='API.igreja')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('capacidade', models.PositiveIntegerField(blank=True, null=True)),
                ('equipamentos', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='API.igreja')),
            ],
            options={
                'verbose_name': 'Sala / Local',
                'verbose_name_plural': 'Salas / Locais',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='API.sala'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('abstencao', 'Abstenção')], max_length=10)),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='API.pauta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=80)),
                ('entidade', models.CharField(blank=True, max_length=80)),
                ('entidade_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['entidade', 'entidade_id'], name='API_auditlo_entidad_dbd780_idx'), models.Index(fields=['-criado_em'], name='API_auditlo_criado__5021fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrupoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('membro', 'Membro'), ('secretario', 'Secretário'), ('lider', 'Líder'), ('diretor', 'Diretor')], default='membro', max_length=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('rejeitado', 'Rejeitado'), ('inativo', 'Inativo')], default='pendente', max_length=12)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='API.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_grupo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro de grupo',
                'verbose_name_plural': 'Membros de grupo',
                'indexes': [models.Index(fields=['grupo', 'status'], name='API_grupome_grupo_i_c36c15_idx'), models.Index(fields=['usuario', 'status'], name='API_grupome_usuario_91d360_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'grupo'), name='uniq_grupomembro_usuario_grupo')],
            },
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['igreja', 'ativo'], name='API_grupo_igreja__81d15c_idx'),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['igreja', 'tipo'], name='API_grupo_igreja__5479d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('igreja', 'slug'), name='uniq_grupo_igreja_slug'),
        ),
        migrations.AddIndex(
            model_name='inscricao',
            index=models.Index(fields=['evento', 'status'], name='API_inscric_evento__3e4284_idx'),
        ),
        migrations.AddIndex(
            model_name='inscricao',
            index=models.Index(fields=['usuario', 'status'], name='API_inscric_usuario_60e574_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(fields=('usuario', 'evento'), name='uniq_inscricao_usuario_evento'),
        ),
        migrations.AddIndex(
            model_name='membro',
            index=models.Index(fields=['igreja', 'status'], name='API_membro_igreja__11fcfa_idx'),
        ),
        migrations.AddIndex(
            model_name='membro',
            index=models.Index(fields=['igreja', 'papel'], name='API_membro_igreja__76f268_idx'),
        ),
        migrations.AddIndex(
            model_name='membro',
            index=models.Index(fields=['usuario', 'status'], name='API_membro_usuario_f904b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='membro',
            constraint=models.UniqueConstraint(fields=('usuario', 'igreja'), name='uniq_membro_usuario_igreja'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['grupo', 'criado_em'], name='API_mensage_grupo_i_24261a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['usuario', 'lida', '-criado_em'], name='API_notific_usuario_9007b6_idx'),
        ),
        migrations.AddIndex(
            model_name='pauta',
            index=models.Index(fields=['igreja', 'status', '-criado_em'], name='API_pauta_igreja__fd82cd_idx'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['igreja', 'ativo'], name='API_sala_igreja__d61af8_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['igreja', 'status', 'inicio'], name='API_evento_igreja__18cd37_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['grupo', 'inicio'], name='API_evento_grupo_i_e50468_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['status', 'inicio'], name='API_evento_status_4ff8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['visibilidade', 'status'], name='API_evento_visibil_439701_idx'),
        ),
        migrations.AddIndex(
            model_name='voto',
            index=models.Index(fields=['pauta', 'opcao'], name='API_voto_pauta_i_aee798_idx'),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('pauta', 'usuario'), name='uniq_voto_pauta_usuario'),
        ),
    ]
