# Generated by Django 5.2.4 on 2026-01-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
