# Generated by Django 5.2.1 on 2026-06-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='quorum_minimo',
            field=models.PositiveIntegerField(blank=True, help_text='Nº mínimo de votos para encerrar a pauta automaticamente.', null=True),
        ),
    ]
