# Generated by Django 5.2.1 on 2026-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_pauta_quorum_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomembro',
            name='motivo_rejeicao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='membro',
            name='motivo_rejeicao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
