# Generated by Django 5.2.4 on 2026-01-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_mode',
            field=models.CharField(choices=[('CONFIRM', 'Confirm presence'), ('PARTICIPATE', 'Participate')], default='CONFIRM', max_length=20),
        ),
    ]
