# Generated by Django 5.2.1 on 2026-06-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_grupomembro_motivo_rejeicao_membro_motivo_rejeicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='aplicada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='decisao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pauta',
            name='opcoes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='permitir_justificativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='tipo',
            field=models.CharField(choices=[('alteracao_igreja', 'Alteração de dados da igreja'), ('criar_grupo', 'Criar grupo'), ('criar_sala', 'Criar sala/local'), ('agendar_evento', 'Agendar evento'), ('enquete_livre', 'Enquete livre'), ('outra', 'Outra deliberação')], default='outra', max_length=20),
        ),
        migrations.AlterField(
            model_name='voto',
            name='opcao',
            field=models.CharField(max_length=50),
        ),
    ]
