# Generated by Django 5.2.1 on 2026-06-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_pauta_aplicada_em_pauta_decisao_pauta_opcoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='categoria',
            field=models.CharField(choices=[('infraestrutura', 'Infraestrutura'), ('programacao', 'Programação'), ('financeiro', 'Financeiro'), ('grupos', 'Grupos'), ('pessoal', 'Pessoal'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
        migrations.AddField(
            model_name='pauta',
            name='metodo_votacao',
            field=models.CharField(choices=[('unanimidade', 'Unanimidade (todos precisam aprovar)'), ('maioria_simples', 'Maioria simples (mais sim que não)'), ('maioria_absoluta', 'Maioria absoluta (>50% dos anciões)'), ('dois_tercos', 'Dois terços dos votos válidos'), ('quorum_aprovacao', 'Nº mínimo de votos sim'), ('lider', 'Aprovação simples (1 voto sim basta)')], default='maioria_simples', max_length=20),
        ),
        migrations.AlterField(
            model_name='pauta',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('encerrada', 'Encerrada'), ('expirada_sem_quorum', 'Expirada sem quórum')], default='aberta', max_length=20),
        ),
    ]
