# Generated by Django 5.2.1 on 2026-06-08 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_pauta_categoria_pauta_metodo_votacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='cor',
            field=models.CharField(default='#64748b', max_length=7),
        ),
        migrations.AddField(
            model_name='igreja',
            name='cor_primaria',
            field=models.CharField(default='#16a34a', max_length=7),
        ),
        migrations.CreateModel(
            name='IgrejaSeguidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='API.igreja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igrejas_seguidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguidor de igreja',
                'verbose_name_plural': 'Seguidores de igreja',
                'indexes': [models.Index(fields=['usuario'], name='API_igrejas_usuario_6f6597_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'igreja'), name='uniq_seguidor_usuario_igreja')],
            },
        ),
    ]
