# Generated by Django 5.2.4 on 2026-01-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_portuguese_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventParticipation',
        ),
        migrations.DeleteModel(
            name='EventUpdate',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='TeamChatMessage',
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
        migrations.DeleteModel(
            name='TeamRole',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='ChurchStaff',
        ),
        migrations.DeleteModel(
            name='OperatingHour',
        ),
        migrations.DeleteModel(
            name='OperatingException',
        ),
        migrations.DeleteModel(
            name='Church',
        ),
    ]
