# Generated by Django 5.2.1 on 2026-06-08 05:16

import API.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_grupo_cor_igreja_cor_primaria_igrejaseguidor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PautaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(blank=True, null=True)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_pauta', to=settings.AUTH_USER_MODEL)),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='API.pauta')),
            ],
            options={
                'verbose_name': 'Comentário de pauta',
                'verbose_name_plural': 'Comentários de pauta',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PautaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=API.models._anexo_path)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('tamanho_bytes', models.PositiveIntegerField(default=0)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_pauta', to=settings.AUTH_USER_MODEL)),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='API.pauta')),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='API.pautacomentario')),
            ],
            options={
                'verbose_name': 'Anexo de pauta',
                'verbose_name_plural': 'Anexos de pauta',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='pautacomentario',
            index=models.Index(fields=['pauta', 'criado_em'], name='API_pautaco_pauta_i_aa5b45_idx'),
        ),
    ]
