# Generated by Django 5.2.1 on 2026-06-10 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_pautacomentario_pautaanexo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EnqueteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('multipla_escolha', models.BooleanField(default=False)),
                ('anonima', models.BooleanField(default=False)),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquetes_criadas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes', to='API.grupo')),
            ],
            options={
                'verbose_name': 'Enquete de grupo',
                'verbose_name_plural': 'Enquetes de grupo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='mensagem',
            name='enquete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagem', to='API.enquetegrupo'),
        ),
        migrations.CreateModel(
            name='EnqueteOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='API.enquetegrupo')),
            ],
            options={
                'verbose_name': 'Opção de enquete',
                'verbose_name_plural': 'Opções de enquete',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnqueteVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='API.enqueteopcao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_enquete', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto de enquete',
                'verbose_name_plural': 'Votos de enquete',
            },
        ),
        migrations.AddIndex(
            model_name='enquetegrupo',
            index=models.Index(fields=['grupo', 'criado_em'], name='API_enquete_grupo_i_b52999_idx'),
        ),
        migrations.AddConstraint(
            model_name='enquetevoto',
            constraint=models.UniqueConstraint(fields=('opcao', 'usuario'), name='uniq_voto_enquete_opcao_usuario'),
        ),
    ]
