# Generated by Django 5.2.1 on 2026-06-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_mensagem_conteudo_enquetegrupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='canal',
            field=models.CharField(choices=[('anciaos', 'Canal dos Anciões'), ('lideranca', 'Canal da Liderança')], default='anciaos', help_text='Eleitorado: anciões (governança) ou líderes de igreja (liderança).', max_length=12),
        ),
        migrations.AlterField(
            model_name='membro',
            name='papel',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('membro', 'Membro'), ('lider_igreja', 'Líder de igreja'), ('anciao', 'Ancião'), ('pastor', 'Pastor'), ('admin_igreja', 'Administrador da igreja')], default='visitante', max_length=20),
        ),
    ]
