# Generated by Django 5.2.1 on 2026-06-10 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_pauta_canal_alter_membro_papel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='secretaria',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada')], default='rascunho', max_length=12)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas_criadas', to=settings.AUTH_USER_MODEL)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atas', to='API.igreja')),
                ('pauta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ata', to='API.pauta')),
                ('publicada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas_publicadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ata',
                'verbose_name_plural': 'Atas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['igreja', 'status', '-criado_em'], name='API_ata_igreja__24a7e7_idx')],
            },
        ),
    ]
