# Generated by Django 5.2.1 on 2026-06-10 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_membro_secretaria_ata'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='papel_desde',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
